<?php

namespace app\models;

use Yii;
use app\models\traits\SafeDeleteTrait;

/**
 * This is the model class for table "{{%type_wagon}}".
 *
 * @property string $id
 * @property string $type
 * @property integer $enabled
 * @property integer $deleted
 * @property string $deleted_at
 */
class TypeWagon extends \yii\db\ActiveRecord
{
    use SafeDeleteTrait {
        init as traitInit;
        beforeSafeDelete as traitBeforeSafeDelete;
        safeDelete as traitSafeDelete;
        afterSafeDelete as traitAfterSafeDelete;
    }

    public function init()
    {
        parent::init();
        $this->traitInit();
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%type_wagon}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type'], 'required'],
            [['enabled', 'deleted'], 'integer'],
            [['deleted_at'], 'safe'],
            [['id'], 'integer'],
            [['type'], 'string', 'max' => 40],
            [['id'], 'unique'],
            [['type'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Род вагона',
            'enabled' => 'Доступен',
            'deleted' => 'Удален',
            'deleted_at' => 'Удален в',
        ];
    }

    public function beforeSave($insert)
    {
        $this->deleted_at = '0000-00-00 00:00:00';

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
